# Generated by Django 2.2.3 on 2019-10-17 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20191016_1728'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='status',
            table='Status',
        ),
    ]
