# Generated by Django 2.2.3 on 2019-07-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_no', models.IntegerField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('job_designation', models.CharField(max_length=50)),
                ('manager_id', models.IntegerField(default=None)),
                ('date_of_birth', models.DateField()),
                ('salary', models.IntegerField()),
                ('commission_amount', models.IntegerField(default=None)),
                ('dept_no', models.IntegerField()),
            ],
        ),
    ]
