# Generated by Django 2.2.3 on 2019-10-17 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='update',
            table='Update',
        ),
    ]
